name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: make test

      - name: Build executable
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fbimage_display
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fbimage_display
          path: build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/fbimage_display
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}